// Define player data with unique skills for modals and specials for in-game attacks
window.players = [
    { id: 'hero-1', firstName: 'Iron', lastName: 'Man', realName: 'Tony Stark', weapon: 'Iron Man Armor', photo: 'imgs/iron man.png', skill: 'Genius Inventor: Designs advanced tech on the fly.', special: 'Repulsor Barrage: Fires a focused energy blast at one enemy.' },
    { id: 'hero-2', firstName: 'Captain', lastName: 'America', realName: 'Steve Rogers', weapon: 'Vibranium Shield', photo: 'imgs/capam.png', skill: 'Tactical Leadership: Inspires and coordinates allies.', special: 'Shield Bash: Stuns a single enemy for one turn.' },
    { id: 'hero-3', firstName: 'Thor', lastName: 'Odinson', realName: 'Thor Odinson', weapon: 'Mjolnir', photo: 'imgs/thor.png', skill: 'Storm Summoning: Controls lightning and storms.', special: 'Thunder Strike: Deals heavy damage to one enemy with a lightning bolt.' },
    { id: 'hero-4', firstName: 'Black', lastName: 'Widow', realName: 'Natasha Romanoff', weapon: 'Electroshock Batons', photo: 'imgs/widow.png', skill: 'Master Espionage: Infiltrates and gathers intel.', special: 'Stealth Strike: Attacks with increased critical chance.' },
    { id: 'hero-5', firstName: 'Hawkeye', lastName: '', realName: 'Clint Barton', weapon: 'Bow and Trick Arrows', photo: 'imgs/hawkeye.png', skill: 'Precision Aim: Never misses a target.', special: 'Explosive Arrow: Damages all enemies in a small area.' },
    { id: 'hero-6', firstName: 'Spider', lastName: 'Man', realName: 'Peter Parker', weapon: 'Web-shooters', photo: 'imgs/spiderman.png', skill: 'Spider-Sense: Detects imminent danger.', special: 'Web Trap: Immobilizes an enemy, preventing their next action.' },
    { id: 'hero-7', firstName: 'Doctor', lastName: 'Strange', realName: 'Stephen Strange', weapon: 'Mystic Arts / Eye of Agamotto', photo: 'imgs/strange.png', skill: 'Dimensional Manipulation: Opens portals across realms.', special: 'Time Loop: Resets health of one ally to its starting value.' },
    { id: 'hero-8', firstName: 'Black', lastName: 'Panther', realName: 'T’Challa', weapon: 'Vibranium Suit and Claws', photo: 'imgs/panther.png', skill: 'Kinetic Energy Absorption: Stores and redirects energy.', special: 'Vibranium Slash: Deals damage and absorbs some for self-healing.' },
    { id: 'hero-9', firstName: 'Scarlet', lastName: 'Witch', realName: 'Wanda Maximoff', weapon: 'Chaos Magic', photo: 'imgs/witch.png', skill: 'Reality Warping: Alters reality with a thought.', special: 'Hex Bolt: Randomly reduces an enemy’s attack or health.' },
    { id: 'hero-10', firstName: 'Ant', lastName: 'Man', realName: 'Scott Lang', weapon: 'Pym Particles Suit', photo: 'imgs/antman.png', skill: 'Size Manipulation: Shrinks or grows instantly.', special: 'Giant Stomp: Deals massive damage to one enemy.' },
    { id: 'hero-11', firstName: 'Wolverine', lastName: '', realName: 'James Howlett/Logan', weapon: 'Adamantium Claws and Healing Factor', photo: 'imgs/bub.png', skill: 'Berserker Rage: Unleashes unstoppable fury.', special: 'Adamantium Frenzy: Attacks multiple times in one turn.' },
    { id: 'hero-12', firstName: 'Storm', lastName: '', realName: 'Ororo Munroe', weapon: 'Weather Manipulation', photo: 'imgs/storm.png', skill: 'Atmospheric Control: Creates hurricanes or clear skies.', special: 'Tornado Blast: Pushes back all enemies, delaying their actions.' },
    { id: 'hero-13', firstName: 'Cyclops', lastName: '', realName: 'Scott Summers', weapon: 'Optic Blasts', photo: 'imgs/scott.png', skill: 'Energy Beam Precision: Adjusts blast intensity.', special: 'Optic Barrage: Hits all enemies with reduced damage.' },
    { id: 'hero-14', firstName: 'Phoenix', lastName: '', realName: 'Jean Grey Summers', weapon: 'Telepathy and Telekinesis', photo: 'imgs/jean.png', skill: 'Psychic Overload: Overwhelms minds with psychic energy.', special: 'Mind Crush: Deals damage based on target’s remaining health.' },
    { id: 'hero-15', firstName: 'Beast', lastName: '', realName: 'Henry McCoy', weapon: 'Enhanced Strength and Agility', photo: 'imgs/beast.png', skill: 'Scientific Expertise: Solves complex problems instantly.', special: 'Primal Leap: Attacks and boosts own agility for one turn.' },
    { id: 'hero-16', firstName: 'Gambit', lastName: '', realName: 'Remy LeBeau', weapon: 'Charged Playing Cards', photo: 'imgs/gambit.png', skill: 'Kinetic Charge: Infuses objects with explosive energy.', special: 'Ace of Spades: Throws a single card for high damage.' },
    { id: 'hero-17', firstName: 'Rogue', lastName: '', realName: 'Anna Marie', weapon: 'Power Absorption', photo: 'imgs/rogue.png', skill: 'Memory Assimilation: Gains memories of those touched.', special: 'Power Drain: Steals health from an enemy to heal self.' },
    { id: 'hero-18', firstName: 'Deadpool', lastName: '', realName: 'Wade Wilson', weapon: 'Regenerative Healing Factor and Katanas', photo: 'imgs/wade.png', skill: 'Fourth Wall Break: Interacts with narrative reality.', special: 'Chimichanga Bomb: Explosive attack with random extra effects.' },
    { id: 'hero-19', firstName: 'Venom', lastName: '', realName: 'Eddie Brock', weapon: 'Symbiote Powers', photo: 'imgs/venom.png', skill: 'Symbiote Morph: Shapeshifts into weapons or forms.', special: 'Tendril Assault: Attacks all enemies with symbiote tendrils.' },
    { id: 'hero-20', firstName: 'Magneto', lastName: '', realName: 'Max Eisenhardt', weapon: 'Magnetic Fields', photo: 'imgs/max.png', skill: 'Electromagnetic Pulse: Disables all electronics.', special: 'Metal Storm: Crushes one enemy with magnetic force.' },
    { id: 'hero-21', firstName: 'Doctor', lastName: 'Doom', realName: 'Victor Von Doom', weapon: 'Power Armor and Sorcery', photo: 'imgs/doom.png', skill: 'Mystic-Tech Fusion: Combines magic and technology.', special: 'Doom’s Curse: Applies a damage-over-time effect to one enemy.' },
    { id: 'hero-22', firstName: 'Thanos', lastName: '', realName: 'Thanos', weapon: 'Infinity Gauntlet', photo: 'imgs/thanos.png', skill: 'Cosmic Domination: Commands universal forces.', special: 'Infinity Snap: Instantly defeats a weakened enemy.' },
    { id: 'hero-23', firstName: 'Loki', lastName: '', realName: 'Loki Laufeyson', weapon: 'Sorcery and Illusions', photo: 'imgs/loki.png', skill: 'Shape-shifting: Transforms into any form.', special: 'Illusionary Double: Creates a decoy to absorb one attack.' },
    { id: 'hero-24', firstName: 'Ultron', lastName: '', realName: 'Ultron', weapon: 'Artificial Intelligence and Energy Blasts', photo: 'imgs/ai.png', skill: 'Network Hijacking: Controls digital systems.', special: 'Data Corruption: Reduces an enemy’s attack permanently.' },
    { id: 'hero-25', firstName: 'Red', lastName: 'Skull', realName: 'Johann Schmidt', weapon: 'Cosmic Cube', photo: 'imgs/skull.png', skill: 'Strategic Manipulation: Orchestrates complex schemes.', special: 'Cube Surge: Boosts all allies’ attack for one turn.' },
    { id: 'hero-26', firstName: 'Green', lastName: 'Goblin', realName: 'Norman Osborn', weapon: 'Pumpkin Bombs and Goblin Glider', photo: 'imgs/osborn.png', skill: 'Insanity Inducing Gas: Disorients foes with chemicals.', special: 'Pumpkin Barrage: Throws multiple bombs at random enemies.' },
    { id: 'hero-27', firstName: 'Kingpin', lastName: '', realName: 'Wilson Fisk', weapon: 'Superhuman Strength and Criminal Empire', photo: 'imgs/fisk.png', skill: 'Criminal Overlord: Controls underworld networks.', special: 'Crushing Blow: Deals high damage to one enemy.' },
    { id: 'hero-28', firstName: 'Black', lastName: 'Cat', realName: 'Felicia Hardy', weapon: 'Enhanced Agility and Luck Manipulation', photo: 'imgs/cat.png', skill: 'Probability Shift: Alters luck in her favor.', special: 'Lucky Strike: Guarantees a critical hit on one enemy.' },
    { id: 'hero-29', firstName: 'Mysterio', lastName: '', realName: 'Quentin Beck', weapon: 'Illusions and Special Effects', photo: 'imgs/illusion.png', skill: 'Holographic Deception: Creates lifelike illusions.', special: 'Smoke and Mirrors: Confuses all enemies, reducing accuracy.' },
    { id: 'hero-30', firstName: 'Rhino', lastName: '', realName: 'Aleksei Sytsevich', weapon: 'Superhuman Strength and Durability', photo: 'imgs/rhino.png', skill: 'Unstoppable Charge: Crushes obstacles in a rampage.', special: 'Rhino Rush: Charges through, damaging multiple enemies.' },
    { id: 'hero-31', firstName: 'Sand', lastName: 'Man', realName: 'Flint Marko', weapon: 'Sand Manipulation', photo: 'imgs/sand.png', skill: 'Sand Reformation: Rebuilds body from sand particles.', special: 'Sandstorm: Blinds enemies, reducing their attack.' },
    { id: 'hero-32', firstName: 'Electro', lastName: '', realName: 'Max Dillon', weapon: 'Electricity Manipulation', photo: 'imgs/dillon.png', skill: 'Power Surge: Overloads electrical systems.', special: 'Volt Surge: Chains lightning to hit multiple enemies.' },
    { id: 'hero-33', firstName: 'Doctor', lastName: 'Octopus', realName: 'Otto Octavius', weapon: 'Mechanical Arms', photo: 'imgs/ock.png', skill: 'Multitasking Mastery: Controls arms independently.', special: 'Tentacle Slam: Attacks up to three enemies at once.' },
    { id: 'hero-34', firstName: 'Kraven', lastName: 'the Hunter', realName: 'Sergei Kravinoff', weapon: 'Enhanced Strength and Tracking', photo: 'imgs/hunt.png', skill: 'Predator Instinct: Tracks prey across any terrain.', special: 'Hunter’s Trap: Immobilizes one enemy for two turns.' },
    { id: 'hero-35', firstName: 'Shocker', lastName: '', realName: 'Herman Schultz', weapon: 'Vibro-smash Gauntlets', photo: 'imgs/shock.png', skill: 'Shockwave Burst: Emits area-wide vibrations.', special: 'Vibro-Pulse: Disrupts all enemies, delaying their actions.' },
    { id: 'hero-36', firstName: 'Scorpion', lastName: '', realName: 'Mac Gargan', weapon: 'Mechanical Tail and Enhanced Strength', photo: 'imgs/sting.png', skill: 'Venomous Sting: Paralyzes with tail strike.', special: 'Toxic Tail: Poisons one enemy, dealing damage over time.' },
    { id: 'hero-37', firstName: 'Vulture', lastName: '', realName: 'Adrian Toomes', weapon: 'Winged Flight and Enhanced Strength', photo: 'imgs/prey.png', skill: 'Aerial Assault: Dive-bombs with precision.', special: 'Talon Dive: Strikes one enemy, ignoring their defenses.' }
];

// Fallback for image loading issues
window.players.forEach(player => {
    player.photo = player.photo || 'https://via.placeholder.com/150?text=No+Image';
});